# Generated by Django 3.0.2 on 2020-09-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnloggedUser',
            fields=[
                ('userID', models.TextField(default='', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StateMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unloggedUser', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='unlogged_user_of', to='simulators.UnloggedUser')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('currentStateOf', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_state_of', to='simulators.StateMachine')),
                ('initialStateOf', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_state_of', to='simulators.StateMachine')),
                ('stateMachineOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulators.StateMachine')),
            ],
        ),
    ]
