# Generated by Django 3.0.2 on 2020-09-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
