# Generated by Django 3.0.2 on 2020-09-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0002_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='left',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='state',
            name='top',
            field=models.FloatField(default=0.0),
        ),
    ]
