# Generated by Django 3.0.2 on 2020-09-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0003_auto_20200906_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='paths',
            field=models.ManyToManyField(related_name='_state_paths_+', to='simulators.State'),
        ),
    ]
